version: "3.3"

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "proxydetector"
    restart: unless-stopped
    expose:
      - "1001"
    networks:
      - web
    command:
      - "--providers.docker.network=traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.port=1001"
      - "traefik.docker.network=web"
      - "traefik.http.routers.proxydetector.rule=Host(`zieger.dev`)"
      - "traefik.http.routers.proxydetector.entrypoints=websecure"
      - "traefik.http.routers.proxydetector.tls.certresolver=myresolver"
      - "traefik.http.routers.proxydetector.middlewares=compression, ratelimit"


networks:
  web:
    external: true