version: "3.3"

services:
  proxydetector:
    build:
      context: .
    container_name: "proxydetector"
    restart: unless-stopped
    expose:
      - 1001
    #ports:
    #  - "1001:80"
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=1001"
      - "traefik.http.routers.proxydetector.rule=Host(`zieger.dev`)"
      - "traefik.http.routers.proxydetector.entrypoints=websecure"
      - "traefik.http.routers.proxydetector.tls.certresolver=myresolver"
      - "traefik.http.routers.proxydetector.middlewares=compression, ratelimit"

networks:
  default:
    external:
      name: web